export const MARKDOWN = "markdown"
export const COMPONENTS = "components"

export const SET_IS_USER_LOGGED_IN = "setIsUserLoggedIn"
export const UPDATE_DEFAULT_THEME_OBJECT = "updateDefaultThemeObject"
export const SET_IS_NAV_OPEN = "setIsNavOpen"
export const SET_FULL_SCREEN = "setIsFullScreen"
export const SET_IS_SOURCE_VISIBLE = "setIsSourceVisible"
export const SET_FILTER_CHILDREN = "setFilterChildren"
export const SET_IS_EDITOR_WIDTH_COLLAPSED = "setIsEditorWidthCollapsed"
export const SET_IS_EDITOR_HEIGHT_COLLAPSED = "setIsEditorHeightCollapsed"
